n = input('Digite algo:')
print('O tipo primitivo desse valor é ', type(n))
print('Só tem espaços?', n.isspace())
print('É um numerico?', n.isnumeric())
print('É alfabetico?' , n.isalpha())
print('É alfanumerico?', n.isalnum())
print('É minusculo?', n.islower())
print('É maisculo?', n.isupper())
print('Esta capitalizada?', n.istitle())
